name: Create translation pull request

on:
  push:
    branches: [ main ]
    paths:
    - '**.en.resx'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: resource-translator
        uses: IEvangelist/resource-translator@v2.0.1
        with:
          subscriptionKey: ${{ secrets.AZURE_TRANSLATOR_SUBSCRIPTION_KEY }}
          endpoint: ${{ secrets.AZURE_TRANSLATOR_ENDPOINT }}
          region: ${{ secrets.AZURE_TRANSLATOR_REGION }}
          sourceLocale: 'en'

      - name: create-pull-request
        uses: peter-evans/create-pull-request@v3.4.1
        if: ${{ steps.resource-translator.outputs.has-new-translations }}
        with:
          title: ${{ steps.resource-translator.outputs.summary-title }}
          commit-message: ${{ steps.resource-translator.outputs.summary-details }}