name: Create translation pull request

on:
  push:
    branches: [ main ]
    paths:
    - '**.resx'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Resource translator
        uses: IEvangelist/resource-translator@v1.0.2-preview6
        with:
          subscriptionKey: ${{ secrets.AZURE_TRANSLATOR_SUBSCRIPTION_KEY }}
          endpoint: ${{ secrets.AZURE_TRANSLATOR_ENDPOINT }}
          region: ${{ secrets.AZURE_TRANSLATOR_REGION }}
          sourceLocale: 'en'

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3.4.1
